### PR TITLE
Rename compartments/parameters etc to match paper notation

### PR DESCRIPTION
**Pull request by edknock**
Renamed compartments as follows:

- `I_asympt` -> `I_A`
- `I_sympt` -> `I_C`
- `I_comm_D` -> `G_D`
- `I_hosp_R` -> `H_R`
- `I_hosp_D` -> `H_D`
- `I_ICU_D` -> `ICU_D`
- `I_ICU_S_R` -> `ICU_W_R`
- `I_ICU_S_D` -> `ICU_W_D`
- `R_stepdown_D` -> `W_D`
- `R_stepdown_R` -> `W_R`
- `PCR_pre` -> `T_PCR_pre`
- `PCR_pos` -> `T_PCR_pos`
- `PCR_neg` -> `T_PCR_neg`
- `R_pre` -> `T_sero_pre`
- `R_pos` -> `T_sero_pos`
- `R_neg` -> `T_sero_neg`

Renamed gammas as follows:
- `gamma_asympt` -> `gamma_A`
- `gamma_sympt` -> `gamma_C`
- `gamma_comm_D` -> `gamma_G_D`
- `gamma_hosp_R` -> `gamma_H_R`
- `gamma_hosp_D` -> `gamma_H_D`
- `gamma_ICU_S_R` -> `gamma_ICU_W_R`
- `gamma_ICU_S_D` -> `gamma_ICU_W_D`
- `gamma_stepdown_R` -> `gamma_W_R`
- `gamma_stepdown_D` -> `gamma_W_D`
- `gamma_R_pre_1` -> `gamma_sero_pre_1`
- `gamma_R_pre_2` -> `gamma_sero_pre_2`
- `gamma_R_pos` -> `gamma_sero_pos`
- `gamma_test` -> `gamma_U`

Renamed s parameters as follows:
- `s_asympt` -> `k_A`
- `s_sympt` -> `k_C`
- `s_E` -> `k_E`
- `s_comm_D` -> `k_G_D`
- `s_hosp_R` -> `k_H_R`
- `s_hosp_D` -> `k_H_D`
- `s_ICU_pre` -> `k_ICU_pre`
- `s_ICU_D` -> `k_ICU_D`
- `s_ICU_S_R` -> `k_ICU_W_R`
- `s_ICU_S_D` -> `k_ICU_W_D`
- `s_stepdown_R` -> `k_W_R`
- `s_stepdown_D` -> `k_W_D`
- `s_R_pos` -> `k_sero_pos`
- `s_PCR_pre` -> `k_PCR_pre`
- `s_PCR_pos` -> `k_PCR_pos`

Renamed probability parameters as follows:
- `p_sympt` -> `p_C`
- `p_hosp_sympt` -> `p_H`
- `p_hosp_sympt_step` -> `p_H_step`
- `psi_hosp_sympt` -> `psi_H`
- `p_death_comm` -> `p_G_D`
- `p_death_comm_step` -> `p_G_D_step`
- `psi_death_comm` -> `psi_G_D`
 - `p_death_hosp_D` -> `p_H_D`
- `p_death_hosp_D_step` -> `p_H_D_step`
- `psi_death_hosp_D` -> `psi_H_D`
- `p_death_ICU` -> `p_ICU_D`
- `p_death_ICU_step` -> `p_ICU_D_step`
- `psi_death_ICU` -> `psi_ICU_D`
- `p_death_stepdown` -> `p_W_D`
- `p_death_stepdown_step` -> `p_W_D_step`
- `psi_death_stepdown` -> `psi_W_D`
- `p_admit_conf` -> `p_star`
- `p_admit_conf_step` -> `p_star_step`
- `psi_admit_conf` -> `psi_star`
- `p_seroconversion` -> `p_sero_pos`

Renamed k parameters as follows:
- `k_ICU` -> `kappa_ICU`
- `k_general` -> `kappa_general`
- `k_hosp` -> `kappa_hosp`
- `k_death_hosp` -> `kappa_death_hosp`
- `k_death_comm` -> `kappa_death_comm`
- `k_death` -> `kappa_death`
- `k_admitted` -> `kappa_admitted`
- `k_new` -> `kappa_new`
- `k_new_admitted` -> `kappa_new_admitted`
- `k_pillar2_cases` -> `kappa_pillar2_cases`
 
Other parameters
- `comm_D_transmission` -> `G_D_transmission`
- `C_1` -> `m_CHW`
- `C_2` -> `m_CHR`
- `prop_noncovid_sympt` -> `p_NC`

### CODE REVIEW

**Comment by annecori** [comment]
I've started reviewing this and it seems ok but a few comments:
- I would maybe consider sticking to rel_p_sympt and rel_p_hosp_if_sympt rather than rel_p_C and rel_p_H. I see the rationale for having things self-consistent but we're going to manipulate the vaccine efficacy parameters a lot and I don't think the new notation is particularly intuitive. Happy to hear thoughts from @edknock @pabloperguz @lwhittles  in particular
- we have prob_ICU[i] = p_ICU * psi_ICU[I]. And same for all age dependant probabilities. Would p_ICU_by_age be more specific than prob_ICU? Again thoughts welcome
- We have mix of star and unconf/conf for the cases in hospital with and without a diagnosis. I would harmonise (probably to unconfined/conf everywhere). Particularly problematic is prob_admit_conf[i] = p_star * psi_star[I] which is not consistent
- I find all the double letters for flows very hard to read. E.g. p_II_A. Could this be p_I_A_out? Similarly, not sure what n_TT_sero_pre is supposed to be. n_T_sero_pre_out?

**Comment by edknock** [comment]
> * I would maybe consider sticking to rel_p_sympt and rel_p_hosp_if_sympt rather than rel_p_C and rel_p_H. I see the rationale for having things self-consistent but we're going to manipulate the vaccine efficacy parameters a lot and I don't think the new notation is particularly intuitive. Happy to hear thoughts from @edknock @pabloperguz @lwhittles  in particular

I am fine if you want me to switch back to rel_p_sympt/rel_p_hosp_if_sympt

> * we have prob_ICU[i] = p_ICU * psi_ICU[I]. And same for all age dependant probabilities. Would p_ICU_by_age be more specific than prob_ICU? Again thoughts welcome

p_ICU_by_age (and similarly for others) sounds good to me.

> * We have mix of star and unconf/conf for the cases in hospital with and without a diagnosis. I would harmonise (probably to unconfined/conf everywhere). Particularly problematic is prob_admit_conf[i] = p_star * psi_star[I] which is not consistent

I think I would rather use p_star here since it's a parameter that appears not only in the paper but also in the model diagram, I just forgot to change prob_admit_conf to prob_star (would change to p_star_by_age)

> * I find all the double letters for flows very hard to read. E.g. p_II_A. Could this be p_I_A_out? Similarly, not sure what n_TT_sero_pre is supposed to be. n_T_sero_pre_out?

A problem here is that e.g. p_GG_D becomes p_G_D, which is already the name of something, and there are several cases of that. In general the p_XX are probabilities of progressing through a stage in X, and n_XX give the number progressing stages in X (which can include those leaving X).

**Comment by annecori** [comment]
Further thoughts:
- I would maybe consider sticking to rel_p_sympt and rel_p_hosp_if_sympt rather than rel_p_C and rel_p_H. I see the rationale for having things self-consistent but we're going to manipulate the vaccine efficacy parameters a lot and I don't think the new notation is particularly intuitive. Happy to hear thoughts from @edknock @pabloperguz @lwhittles in particular

EK: I am fine if you want me to switch back to rel_p_sympt/rel_p_hosp_if_sympt

--> I don't feel very strongly about that so whichever you think is best, perhaps in agreement with the others. Will make it easier to adapt the vaccination tasks in ncos-outputs if we keep  rel_p_sympt/rel_p_hosp_if_sympt but that's also not very hard to change.

- we have prob_ICU[i] = p_ICU * psi_ICU[I]. And same for all age dependant probabilities. Would p_ICU_by_age be more specific than prob_ICU? Again thoughts welcome
p_ICU_by_age (and similarly for others) sounds good to me.

EK: We have mix of star and unconf/conf for the cases in hospital with and without a diagnosis. I would harmonise (probably to unconfined/conf everywhere). Particularly problematic is prob_admit_conf[i] = p_star * psi_star[I] which is not consistent
I think I would rather use p_star here since it's a parameter that appears not only in the paper but also in the model diagram, I just forgot to change prob_admit_conf to prob_star (would change to p_star_by_age)

--> Sounds good!

- I find all the double letters for flows very hard to read. E.g. p_II_A. Could this be p_I_A_out? Similarly, not sure what n_TT_sero_pre is supposed to be. n_T_sero_pre_out?

EK: A problem here is that e.g. p_GG_D becomes p_G_D, which is already the name of something, and there are several cases of that. In general the p_XX are probabilities of progressing through a stage in X, and n_XX give the number progressing stages in X (which can include those leaving X).

--> I see. Then maybe just a case of explaining at the start of the odin code in a comment that convention exactly as you've described it here would be ok.

**Comment by edknock** [comment]
@annecori Have changed prob_X to p_X_by_age

Could change p_XX to p_X_progress and n_XX to n_X_progress? I think that's in line with the use of _progress currently?

**Comment by annecori** [comment]
@edknock that is indeed how I've used _progress, so may be good to harmonise...

**Review by annecori — APPROVED** [review]

**Review by pabloperguz — APPROVED** [review]

**Pull request merged**
